# Generated by Django 2.2 on 2019-04-07 17:28

from django.db import migrations, models
import hypereditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', hypereditor.fields.HyperField(default=None)),
            ],
        ),
    ]
